# Generated by Django 6.0.2 on 2026-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.URLField(blank=True),
        ),
    ]
